angular.module('starter')
  // ENGLISH
  .constant('LOCAL_EN', {
    'Back': 'Back',
    'Featured': 'Featured',
    'Search': 'Search',
    'Categories': 'Categories',
    'Cart': 'Cart',
    'Account': 'Account',
    'Shopping Cart': 'Shopping Cart',
    'Add to Cart': 'Add to Cart',
    'All': 'All',
    'Search - e.g \"Dress\"': 'Search - e.g \"Dress\"',
    'No item in cart': 'No item in cart',
    'Checkout': 'Checkout',
    'Reference': 'Reference',
    'Condition': 'Condition',
    'More Info': 'More Info',
    'Features': 'Features',
    'Accessories': 'Accessories',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Close': 'Close',
    'Total': 'Total',
    'Tax': 'Tax',
    'Create an account': 'Create an account',
    'Sign in': 'Sign in',
    'Sign out': 'Sign out',
    'My Account': 'My Account',
    'Order history and details': 'Order history and details',
    'My addresses': 'My addresses',
    'My personal information': 'My personal information',
    'Settings': 'Settings',
    'Change language': 'Change Language',
    'Select languages': 'Select languages',
    'First name': 'First name',
    'Last name': 'Last name',
    'E-mail': 'E-mail',
    'E-mail address': 'E-mail address',
    'Date of Birth': 'Date of Birth',
    'Password': 'Password',
    'Current Password': 'Current Password',
    'New Password': 'New Password',
    'Repeat Password': 'Repeat Password',
    'Confirmation': 'Confirmation',
    'Gender': 'Geschlecht',
    'Please select gender': 'Please select gender',
    'Male': 'Male ',
    'Female': 'Female',
    'No address found': 'No address found',
    'Company': 'Company',
    'Address': 'Address',
    'Address (Line 2)': 'Address (Line 2)',
    'City': 'City',
    'State': 'State',
    'Zip/Postal Code': 'Zip/Postal Code',
    'Country': 'Country',
    'Home phone': 'Home phone',
    'Mobile phone': 'Mobile phone',
    'Additional information': 'Additional information',
    'Please assign an address title for future reference.': 'Please assign an address title for future reference.',
    'Register': 'Register',
    'Save': 'Save',
    'Sign up for our newsletter!': 'Sign up for our newsletter!',
    'Receive special offers!': 'Receive special offers!',
    'No order history': 'No order history',
    'Order history': 'Order history',
    'Order reference': 'Order reference',
    'Date': 'Date',
    'Total price': 'Total price',
    'Payment': 'Payment',
    'Status': 'Status'
  })
  // GERMAN
  .constant('LOCAL_DE', {
    'Back': 'Zurück',
    'Featured': 'Vorgestellte',
    'Search': 'Suche',
    'Categories': 'Kategorien',
    'Cart': 'Warenkorb',
    'Account': 'Konto',
    'Shopping Cart': 'Warenkorb',
    'Add to Cart': 'In den Warenkorb',
    'All': 'Alles',
    'Search - e.g \"Dress\"': 'Suche - z.B. \"Kleid\"',
    'No item in cart': 'Leerer Warenkorb',
    'Checkout': 'Zur Kasse',
    'Reference': 'Artikel-Nr',
    'Condition': 'Zustand',
    'More Info': 'Mehr Infos',
    'Features': 'Eigenschaften',
    'Accessories': 'Zubehör',
    'Edit': 'Bearbeiten',
    'Delete': 'Löschen',
    'Close': 'Schließen',
    'Total': 'Gesamt',
    'Tax': 'MwSt.',
    'Create an account': 'Erstellen Sie ein Konto',
    'Sign in': 'Anmelden',
    'Sign out': 'Abmelden',
    'My Account': 'Ihr Kundenbereich',
    'Order history and details': 'Verlauf und Details Ihrer Bestellungen',
    'My addresses': 'Ihre Adressen',
    'My personal information': 'Ihre persönlichen Daten',
    'Settings': 'Einstellungen',
    'Change language': 'Sprache ändern',
    'Select languages': 'Sprachen auswählen',
    'First name': 'Vorname',
    'Last name': 'Name',
    'E-mail': 'E-mail',
    'E-mail address': 'E-Mail-Adresse',
    'Date of Birth': 'Geburtsdatum',
    'Password': 'Passwort',
    'Current Password': 'Aktuelles Passwort',
    'New Password': 'Neues Passwort',
    'Repeat Password': 'Passwort wiederholen',
    'Confirmation': 'Bestätigung',
    'Gender': 'Geschlecht',
    'Please select gender': 'Bitte wähle ein Geschlecht',
    'Male': 'Männlich ',
    'Female': 'Weiblich',
    'No address found': 'Keine Adresse',
    'Company': 'Firma',
    'Address': 'Adresse',
    'Address (Line 2)': 'Adresszusatz',
    'City': 'Stadt',
    'State': 'Bundesland',
    'Zip/Postal Code': 'PLZ',
    'Country': 'Land',
    'Home phone': 'Festnetznummer',
    'Mobile phone': 'Mobilfunknummer',
    'Additional information': 'Ergänzende Angaben',
    'Please assign an address title for future reference.': 'Geben Sie eine Kurzbezeichnung für diese Adresse ein, um sie künftig leichter zu finden',
    'Register': 'Registrieren',
    'Save': 'Speichern',
    'Sign up for our newsletter!': 'Abonnieren Sie unseren Newsletter!',
    'Receive special offers!': 'Erhalten Sie Sonderangebote!',
    'No order history': 'Keine Bestellverlauf',
    'Order history': 'Bestellverlauf',
    'Order reference': 'Bestell-Nr.',
    'Date': 'Datum',
    'Total price': 'Gesamtpreis',
    'Payment': 'Zahlungsart',
    'Status': 'Status'
  })